workflows:
  android-apk-workflow:
    name: Android APK Build
    instance_type: linux_x2
    environment:
      flutter: stable
      groups:
        - android_keystore
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
