// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPMWbHrxpsU7omLJPEPsur5xJCRNlZAqE',
    appId: '1:384227067713:web:9292dece04bf011ddcc3c0',
    messagingSenderId: '384227067713',
    projectId: 'crm-leads-app-99120',
    authDomain: 'crm-leads-app-99120.firebaseapp.com',
    storageBucket: 'crm-leads-app-99120.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtFGb79aCHX65ZM2fBVd7KRkDeq66HyF0',
    appId: '1:384227067713:android:24b94bb7c78fa625dcc3c0',
    messagingSenderId: '384227067713',
    projectId: 'crm-leads-app-99120',
    storageBucket: 'crm-leads-app-99120.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7bPqnCujb_3YQx1_ZkHlUIObQaUnKhs',
    appId: '1:384227067713:ios:913abd206c2badd7dcc3c0',
    messagingSenderId: '384227067713',
    projectId: 'crm-leads-app-99120',
    storageBucket: 'crm-leads-app-99120.firebasestorage.app',
    iosBundleId: 'com.digitization.crmLeadsApp',
  );
}
